### PR TITLE
Added new obj/row in contributors.json with my info.

### PR DESCRIPTION
**Pull request by nimraayaz01**

### CODE REVIEW

**Review by sohail0992 — APPROVED** [review]

**Comment by msohailse** [comment]
Please sync your fork with the original repo before creating your branch.
If you add your contribution to outdated code it will result in conflict.
Before doing any changes to the code make sure
- sync your fork with the original repo https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
or
- rebase your branch from the original repo main branch https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github

**Review by sohail0992 — CHANGES_REQUESTED** [review]
Please check the conflicts and resolve

**Comment by nimraayaz01** [comment]
Got it, Sir, Thank you so much, I hope all issues resolved.

**Comment by nimraayaz01** [comment]
Hi Sir, I already synced the fork and then synced my branch with it and then added my name after hareera's name but you accepted wajeeha's one mine is still not accepted so its again having conflict.

**Pull request closed without merging**
